name: 'Run prettify'
on:
   pull_request:
   push:
      branches: [main]

permissions: {}

jobs:
   prettier:
      name: Prettier Check
      runs-on: ubuntu-latest
      steps:
         - name: Checkout Repository
           uses: actions/checkout@0717577d45739eb3c851188b29f50ed6c0b2194e # v2

         - name: Enforce Prettier
           uses: actionsx/prettier@8b6d14bd1241e743fa9a6112b43d691d1890a8e9 # v2
           with:
              args: --check .
